name: quizz_app
description: "A new Flutter project."
publish_to: 'none'


version: 1.0.0+1

environment:
  sdk: '>=3.3.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  retrofit: ^4.4.1
  logger: ^2.4.0  # for logging purpose
  json_annotation: ^4.9.0
  cupertino_icons: ^1.0.6
  lottie: ^3.1.2
  google_fonts: ^6.2.1
  flutter_screenutil: ^5.9.3
  dio: ^5.7.0
  injectable: ^2.5.0
  flutter_bloc: ^8.1.6
  get_it:
  hive: ^2.2.3
  flutter_localizations:
    sdk: flutter
  intl: ^0.19.0
  hive_flutter: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
    # add the generator to your dev_dependencies
  injectable_generator:
# add build runner if not already added
  flutter_lints: ^3.0.0
  retrofit_generator: '>=8.0.0 <10.0.0' # for Dart 3.3 use ^9.0.0
  build_runner: ^2.3.3
  json_serializable: ^6.8.0
  hive_generator:


flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/animations/
    - assets/images/
    - assets/icons/

