name: quizz_app
description: "A new Flutter project."
publish_to: 'none'


version: 1.0.0+1

environment:
  sdk: '>=3.3.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.6
  lottie: ^3.1.2
  google_fonts: ^6.2.1
  flutter_screenutil: ^5.9.3
  dio: ^5.7.0
  injectable: ^2.5.0
  flutter_bloc: ^8.1.6
  get_it:

dev_dependencies:
  flutter_test:
    sdk: flutter
    # add the generator to your dev_dependencies
  injectable_generator:
# add build runner if not already added
  build_runner:
  flutter_lints: ^3.0.0


flutter:

  uses-material-design: true

  assets:
    - assets/animations/
    - assets/images/
    - assets/icons/

