name: Flutter Dependencies

on:
  pull_request:
    branches:
      - development
      - mail
jobs:
  dependencies:
    name: Get Dependencies
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Pub get
        run: flutter pub get