sealed class ForgetPasswordScreenState{}

class InitialScreenState extends ForgetPasswordScreenState{}
class NavigateToEmailVerificationScreenState extends ForgetPasswordScreenState{}
class NavigateToResetPasswordScreenState extends ForgetPasswordScreenState{}